# Default values for rducm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/rducm
  pullPolicy: Always

preJob:
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  timeout: 1200
  preInitDB:
    # 是否初始化groovy脚本或excel数据
    enable: false
    # 初始化数据库配置
    datasource:
      url: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: hzero
      password: hzero

env:
  open:
    # 是否自动刷新服务权限
    CHOERODON_EUREKA_EVENT_PARSE_PERMISSION: true
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka/
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: false
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://dev.hzero.org:8010/
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hzero
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hzero
    # Redis host
    SPRING_REDIS_HOST: redis.hzero.org
    # Redis DB
    SPRING_REDIS_DATABASE: 1
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 30000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 3000
    # 日志级别
#    LOGGING_LEVEL: info

    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m

metrics:
  path: /prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false

service:
  enabled: false
  type: ClusterIP
  port: 7140
  name: rducm
deployment:
  # 管理端口
  managementPort: 7141

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi

# 服务治理相关配置
hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT
